### ISSUE TITLE
ScrollToEvents

### ISSUE THREAD

**Issue by Lucienzera** [erksch/react-native-wheely#15]
Is there away to surface the scrollToIndex events since the elements are using flatlist to handle index snap to specific index based on onPressed?

**Comment by erksch** [comment]
Good idea, we could add a prop and pass it through or allow setting props of the FlatList in general.

**Comment by Lucienzera** [comment]
Thanks for replying so soon, Could you suggest an approach I should take in order to try and do this and play around with it while waiting for you?

**Comment by erksch** [comment]
Since 0.5.0, you can now add props to the `FlatList` using `flatListProps`. The picker also jumps to the selected index if the value is changed from outside.
