### ISSUE TITLE
Can you remove default sort or add props for change default sort?

### ISSUE THREAD

**Issue by vitalyliber** [erksch/react-native-wheely#2]
Hi! Thank you for this library!

I have a list with dates [1,2,3,4]. But I can't change an order in wheel. I tried to use strings ['1', '2', '3']. But it doesn't work.

**Comment by erksch** [comment]
Hmm, I am not sure if I understand, can't you just the sort the array that you pass to the options prop?

**Comment by erksch** [comment]
Closing this. When you still have an issue feel free to reopen :)
