### ISSUE TITLE
When I use setState to set the options property, However, the old values(by options control) in the view are not updated.

### ISSUE THREAD

**Issue by erksch** [erksch/react-native-wheely#27]
When I use setState to set the options property, However, the old values(by options control) in the view are not updated.

_Originally posted by @daxiangfei in https://github.com/erksch/react-native-wheely/issues/20#issuecomment-1091372488_

**Comment by erksch** [comment]
As described in [the memoization section in README](https://github.com/erksch/react-native-wheely#memoization), the options have to be fixed on the first render. You probably can wrap the picker in a component that renders when the options are available.

**Comment by kuzkokov** [comment]
btw, there is a simpler solution — just use the `key` prop. like this f.e.:
```
const optionLabels = options.map(option => option.label);
return (
  <WheelPicker
    containerStyle={styles.picker}
    decelerationRate="normal"
    itemHeight={40}
    itemTextStyle={styles.pickerItemText}
    key={optionLabels.join('')}
    options={optionLabels}
    selectedIndex={selectedIndexes[index]}
    selectedIndicatorStyle={styles.selectedIndicator}
    visibleRest={2}
    onChange={selected => handlePickerChange(index, selected)}
  />
```
