### ISSUE TITLE
Dispositioned Items

### ISSUE THREAD

**Issue by sidnetopia** [erksch/react-native-wheely#32]
Hi,

Whenever I navigated to the 2nd or 3rd option, it overlaps:
![ezgif-5-52d9efbc96](https://user-images.githubusercontent.com/36142076/178137884-c245355a-07cb-458d-9fec-9d5e1c7f17c3.gif)

If I also resized the height of the container e.g. `containerStyle={{height: '15%'}}`, it offsets the options:
![Screenshot 2022-07-10 164253](https://user-images.githubusercontent.com/36142076/178137916-bd83c8f8-4819-443c-8e7f-6c48356bf178.png)

**Comment by sidnetopia** [comment]
Code for that:
`            <WheelPicker
                selectedIndex={selectedIndex}
                options={['1']}
                onChange={(index) => setSelectedIndex(index)}
                containerStyle={{
                    position: 'relative',
                    // elevation: 12,
                    // borderBottomWidth: 0.5,
                    height: '15%',
                    // top: -50,
                    // backgroundColor: '#ee1',
                }}
                // itemTextStyle={{
                //     // fontSize: 22,
                //     // justifyContent: 'center',
                //     // fontWeight: '100',
                //     top: '-20%',
                // }}
                // itemStyle={{
                //     top: -50,
                // }}
                itemHeight={40}
                selectedIndicatorStyle={{
                    backgroundColor: 'rgba(0, 112, 60, 0.2)',
                    width: '92%',
                    alignSelf: 'center',
                }}
            />
`

**Comment by erksch** [comment]
Changing the `height` like that is not supported.
