### ISSUE TITLE
hello, We need more demonstration cases

### ISSUE THREAD

**Issue by ZhengHong187** [erksch/react-native-wheely#5]
Because there are some complicated APIs, I don't know how to use them

**Comment by erksch** [comment]
Try them out :D

Do you mean the opacity and rotation function?

**Comment by ZhengHong187** [comment]
> Try them out :D
> 
> Do you mean the opacity and rotation function?

yes

**Comment by ZhengHong187** [comment]
and, Why are the big numbers on the top and the small numbers on the bottom
