### ISSUE TITLE
onChange not working with first index?

### ISSUE THREAD

**Issue by nyplex** [erksch/react-native-wheely#60]
It seems that the onChange callback does not return any value when the first option is being selected. Works fine for all the others index in the array.

**Comment by danielkeithw** [comment]
I  am having this issue also -- Did you figure it out?

**Comment by PartypayNL** [comment]
Same issue, cant reselect the first item.

**Comment by PartypayNL** [comment]
@nyplex easy fix:

https://github.com/erksch/react-native-wheely/compare/master...danielkeithw:react-native-wheely:master


@erksch I think this should be merged with main

**Comment by DavidMaza** [comment]
I've also had the above problem where selectedIndex is greater than 0

e.g.

1. Create a wheel with the values: 0, 1, 2, 3
2. Set selectedIndex = "1"
3. Scroll to "2"
4. onChange() is emitted for "2"
5. Scroll to "1"
6. Expected: isChange() is emitted for "1"
    Actual: onChange() is not emitted

https://github.com/erksch/react-native-wheely/compare/master...danielkeithw:react-native-wheely:master fixes it for me
